version: '3'
services:
  login:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=login.py
      - APP_SECRET=testsecret
      - DBURI=postgresql://postgres:docker@dbserver/postgres
    links:
      - postgres:dbserver
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    restart: always
  postgres:
    image: "postgres:12.1"
    environment:
      - POSTGRES_PASSWORD=docker
    restart: always
